MyBitFoundation/MyBit-Go.app

- package.json
closes https://github.com/MyBitFoundation/MyBitDapp-FrontEnd/issues/56
> Update react-jazzicon to ^0.1.0

- src/components/Asset.js
- src/components/ExchangeRate.js
> Add spacing

- src/components/AssetDetails.js
- src/components/ConfirmationPopup.js
- src/stories/constants.js
> Remove expected annual returns

- package-lock.json
- package.json
see https://github.com/ethereum/web3.js/issues/1916
> downgrading web3 due to issue with pulling event logs

- src/components/AppHeader.js
- src/components/Asset.js
- src/components/CategoryFilter.js
- src/styles/Asset.scss
- src/styles/CategoryFilter.scss
> explore improvements

- src/components/AppHeader.js
- src/components/Asset.js
- src/components/BlockchainInfo.js
- src/components/MetamaskChecker.js
- src/constants/index.js
The result of adding the event listener is that if the user logs out or logs in the app reacts instantly. As opposed to the current solution, that refreshes every few seconds.
> Made WatchList only work when user is connected to ethereum and added event listener for when the account changes

- server.js
- src/App.js
- src/apis/brain.js
- src/components/ConfirmationPopup.js
- src/constants/index.js
- src/styles/Asset.scss
- src/styles/AssetDetails.scss
- src/styles/index.scss
For when the user is pulling assets from our server.
> Added metamask error messages under the Header

- components/UI/Asset/AssetTemplate/index.js
We probably won't merge to master for a bit while testing so before we do that we change the flag back.
> Enables Revenue Generation 

- components/KyberContext/index.js
There was a leftover dependency from the first attempt at Kyber integration that is giving us issues right now, related to CORS. Removed that.
> Fixes CORS issue related to Kyber

- components/UI/CivicContext.js
- pages/_app.js
As opposed to having to login every time the user goes to /list-asset
> Makes Civic login last the entire session

- components/UI/Asset/AssetDefault/index.js
assets with a completion percentage of over 99.5% were being rounded up to 100%.
> Fixes Asset bar percentage

- components/AssetDetails/index.js
- components/AssetUpdates/index.js
- components/ThreeBoxContext/index.js
- package.json
- yarn.lock
- Uses Promise.all for a bit of optimization 
- Moves the AM Updates container under the Asset Details container
- Adds scroll to the AM Updates container
- Fixes error when accessing a profile without an avatar
- Showing posts by date in desc order
> Fixes merge conflicts and AM Updates

- components/AssetFundingConfirm/index.js
- pages/list-asset/index.js
- pages/list-asset/listAssetDesktop.js
- pages/list-asset/listAssetMobile.js
- pages/list-asset/slides/collateral.js
I've also changed the implementation of slippage when funding. Before it would hide the row if the slippage was 0%, I removed that so now it shows 0%. We can see what users think once they test it and review it then.
> Adds Slippage percentage to List-asset, collateral slide

- apis/brain.js
- components/AirtableContext.js
- components/AssetDetails/index.js
- components/AssetDetailsInfo/index.js
- components/AssetFundingConfirm/index.js
- components/AssetFundingModule/index.js
- components/BlockchainContext.js
- components/UI/LabelWithTooltip.js
- components/UI/NumericInputWithLabelAndStaticCurrency.js
- constants/airtable.js
- pages/list-asset/index.js
- pages/list-asset/listAssetDesktop.js
- pages/list-asset/listAssetMobile.js
- pages/list-asset/slides/availableAssets.js
- pages/list-asset/slides/generalDescription.js
- server/controllers/airTableController.js
- Adds listing fee due to Fiat to Crypto conversion in List-asset.
- Adds `Additional Costs` to List-asset.
Removes the 8% Funding fee from the Asset Funding breakdown. Please note there is a reference to this fee here:
> Updates funding and list-asset

- components/AppHeader/appHeaderLogo.js
- components/AppHeader/index.js
- components/MobileAccountInfo/index.js
- components/MobileMenu/index.js
- Makes the logo clickable
- Makes the user address clickable and links to its Asset Manager page. 
- Mobile menu updated to close after the user's address is clicked.
> Header updates

- .circleci/config.yml
- .dockerignore
- .travis.yml
- Dockerfile
- package-lock.json
- yarn.lock
* Moved build process to docker to have better environment parity
* Initial steps to future moves to a kubernetes based setup
> Dockerisation migration

- .babelrc
- apis/brain.js
- components/AirtableContext.js
- components/AllAssetManagers/index.js
- components/AssetDetails/index.js
- components/AssetExplorer/index.js
- components/AssetFundingSelector/index.js
- components/BlockchainContext.js
- components/ManageAsset/index.js
- components/ManageAsset/manageAssetAssetInfo.js
- components/ManageAssetModule/index.js
- components/ThreeBoxProfile/index.js
- components/UI/Asset/index.js
- components/UI/CivicContext.js
- constants/airtable.js
- constants/links.js
- constants/localStorageKeys.js
- package.json
- pages/list-asset/index.js
- pages/list-asset/listAssetDesktop.js
- pages/list-asset/listAssetMobile.js
- pages/list-asset/slides/availableAssets.js
- server/.babelrc
- server/controllers/airTableController.js
- server/controllers/assetsController.js
- server/index.js
- utils/ipfs.js
- yarn.lock
- Fixes Civic issue
- Adds caching to 3Box
Still missing the saving of files to complete what is required to have uploaded to IPFS before we can move forward to mainnet. 
I have found other things I'll be fixing in the coming days:
- Metamask logic error that results in a flash of the UI.
- Kyber errors at the beginning.
- Token Selector when user has > 5 tokens
- Replace the address at the top with a username if user is on 3Box
- Asset Manager Profile Popup
> Updates SDK to version 0.0.44 and adds IPFS support. Also changes Airtable Architecture

- components/TokenSelector/index.js
Happened when the user had over 3 different tokens
> Fixes Token Selector overflow issue

- components/AppHeader/appHeaderAddress.js
- components/AppHeader/index.js
- components/ThreeBoxProfile/index.js
- components/UI/Address/index.js
Also adds a lifecycle event to track changes to the address.
> Shows 3Box username instead of Address for User info

- apis/brain.js
- components/AssetDisplayer/index.js
- components/AssetExplorer/index.js
- components/BlockchainContext.js
- components/Portfolio/index.js
- components/UI/Asset/AssetDefault/index.js
- components/UI/Asset/index.js
- components/UI/AssetDeadline/index.js
- components/UI/AssetManagerTooltip.js
- yarn.lock
- Fixed the passing of some objects in `brain.js` when resolving the assets. Still a couple missing in order to optimize renders.
- Refactoring of the `ui/Asset` component.
> Reenables AM Popup in Explore Page

- components/CarouselSlide/components/carouselSlideParagraph.js
- constants/knowledgeBase.js
- package.json
- pages/help/index.js
- pages/list-asset/slides/collateral.js
- yarn.lock
Added '@react-scrollable-anchor' to be able to scroll to a given anchor in the '/help' page. Currently linking to that anchor manually but in the future we can use the constants file that holds the questions (that serve as IDs for anchors) so that we can get a solution that scales better.
> Fixes Learn More in Collateral Slide

- components/TokenSelector/index.js
- pages/help/index.js
- Adds autofocus to the search input
- Fixes help page to start off with 'Value of MyBit Go'
> Fixes TokenSelector Overflow issue

- components/UI/Footer/navigationData.js
- pages/onboarding/index.js
- Also fixes a nav url in the Footer
> Fixes redirect from Onboarding back to the Explore page

- components/AssetManagerFullProfile.js
- components/Loading/index.js
- components/ManageAsset/index.js
- pages/asset/index.js
- Updated Asset Details Page to use the new back button design.
- Updated the Loading component to receive a prop telling what back button to render since some pages can't be updated yet (Manage Asset Page).
> Back button updates

- apis/brain.js
- components/AirtableContext.js
- components/AssetDetailsInfo/index.js
- components/AssetDisplayer/index.js
- components/BlockchainContext.js
- components/CarouselSlide/components/carouselNextButton.js
- components/KyberContext/index.js
- components/MetamaskContext/index.js
- components/UI/CarouselWithNavigation/carouselWithNavigationButton.js
- package.json
- pages/list-asset/customTimeline/index.js
- pages/list-asset/index.js
- server/controllers/awsController.js
- server/index.js
- utils/ipfs.js
- yarn.lock
- Removed some 'console.logs' that were spamming the console a bit 
- Fixed some warnings related to passing props and they ending up in the DOM  
- Updated Airtable code to also take in the files IPFS string; 
- Fixed 'AssetDisplayer' logic for when it should go to page 0; 
- Updated getAssets() in 'AirtableContext' for better syncing between listing the asset and it showing up in the platform.
> Adds IPFS File Upload

- components/AssetFundingConfirm/footer.js
- components/AssetFundingConfirm/index.js
- components/AssetUpdates/index.js
Also fixes the parameters passed when funding. Tested on mainnet with our first asset!
> Hide empty messages in Asset Details Page

- components/FundingCalculator/index.js
- components/UI/TooltipWithQuestionMarkGrey.js
> Adds tooltip to Asset Funding with shares breakdown

- components/Head.js
- components/UI/AssetManagerProfile/index.js
- components/UI/CarouselWithNavigation/carouselWithNavigationButton.js
- components/UI/CarouselWithNavigation/index.js
- next.config.js
- pages/_app.js
- pages/list-asset/customTimeline/index.js
- pages/list-asset/index.js
- pages/list-asset/listAssetDesktop.js
- pages/list-asset/listAssetMobile.js
- pages/list-asset/slides/assetLocation.js
- pages/list-asset/slides/intro.js
- public/index.html
> Remove civic from app

- package.json
- yarn.lock
- Update listing fee collection. (Smart Contracts)
- Update gas limits. (SDK)
> Update MyBit sdk, contracts

- package.json
Update gas limit for investing
> Update gas limit for investing

- components/UI/Footer/navigationData.js
temporarily removed UI from footer, added "report bug"
> updated navigationdata.js
